import type { Metadata } from "next";
import * as Sentry from "@sentry/nextjs";

import "./globals.css";

Sentry.init({
  dsn: "https://205419dab75583bd7fad9a4abc68cdc8@o4506262038052864.ingest.sentry.io/4506262043492352",

  tracesSampleRate: 1.0,

  replaysSessionSampleRate: 0.1,
  replaysOnErrorSampleRate: 1.0,
});

export const metadata: Metadata = {
  title: "Muxlisa.uz",
  description: "Generated by create next app",
};

export default function ClientLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return children;
}
