import type { Metadata } from "next";
import { Inter } from "next/font/google";
import * as Sentry from "@sentry/nextjs";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

Sentry.init({
  dsn: "https://205419dab75583bd7fad9a4abc68cdc8@o4506262038052864.ingest.sentry.io/4506262043492352",

  tracesSampleRate: 1.0,

  replaysSessionSampleRate: 0.1,
  replaysOnErrorSampleRate: 1.0,
});

export const metadata: Metadata = {
  title: "Muxlisa.uz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
